/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.util.Date;
import java.sql.SQLException;
import java.util.List;
import model.Project;
import model.Task;
//import java.util.Date;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {
       
        
        //ProjectController projectController = new ProjectController();
        
          //Project project = new Project();
//        project.setName("Projeto teste");
//        project.setDescription("description");
//        projectController.save(project);
//        
//       
//         project.setId(6);
//         project.setName("Novo nome do projeto");
//         project.setDescription("description");
//         projectController.update(project);
         
//         List<Project> projects = projectController.getAll();
//         System.out.println("Total de projetos = " + projects.size());
//
//         projectController.removeById(7);
         
//         TaskController taskController = new TaskController();
//         
//           Task task = new Task();
//           //task.setIdProject(8);
////           task.setName("testando o sql");
////           task.setDescription("teste");
////           task.setNotes("Sem notas");
////           task.setisIsCompleted(false);
////           task.setDeadline(new Date());
////         
////          taskController.save(task);
//           task.setIdProject(8);
//           task.setName("Alterar telas de aplicação");
//           taskController.update(task);
           
//           List<Task> tasks = taskController.getAll(8);
//           System.out.println("Total de tarefas = " + tasks.size());
             
           // taskController.removeById(5);
         
         
    }
}
